services:
  - type: web
    name: game-app
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: ""
      - key: ADMIN_USERNAME
        value: ""
      - key: ADMIN_PASSWORD
        value: ""
      - key: SESSION_SECRET
        value: ""
      - key: BREVO_API_KEY
        value: ""
      - key: EMAIL_FROM
        value: ""
      - key: EMAIL_TO
        value: ""
